language: python
python:
  - 2.7
  - 3.3
  - 3.4

install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then pip install -r requirements/test-py27.txt; else pip install -r requirements/test.txt; fi
  - pip install coveralls

script:
  - py.test --cov tabular_validator --cov-config .coveragerc --cov-report term-missing

after_success:
  - coveralls
